### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by vivekashok1221** [codephile1221/discordbot#1]
The README.md should list out the available commands and, optionally, other information.

**Comment by KuruvillaJacob02** [comment]
Hi! Could you please assign this issue to me?

**Comment by vivekashok1221** [comment]
Alright, feel free to work on it.
If you have any queries, don't hesitate to reach out to me.
The description of most commands are mentioned in the doc strings.

I will add necessary changes, if felt necessary.
